version: '3'

services:
  scrapy:
    build: .
    image: scrapy
    restart: always
    network_mode: host
    container_name: scrapy
    environment:
      TZ: Asia/Taipei
      GMAIL_USER: a0970366492@gmail.com
      GMAIL_PASSWORD: abcdefg
    ports:
      - '5000:5000'