version: '3'

services:
  scrapy:
    build: .
    image: scrapy
    restart: always
    container_name: scrapy
    environment:
      TZ: Asia/Taipei
      GMAIL_USER: a0970366492@gmail.com
      GMAIL_PASSWORD: 
    ports:
      - '5000:5000'
    volumes:
      - /data:/data
